name: CI

on: [push]

jobs:
  lint:
    name: Lint ðŸ’…
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/prepare
      - uses: quilt-framework/action-lint@v2
        with:
          command: pnpm lint

  type-check:
    name: Type check ðŸ§®
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/prepare
      - uses: quilt-framework/action-type-check@v2
        with:
          command: pnpm type-check

  unit-tests:
    name: Unit tests ðŸ§ª
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/prepare
      # We need to build a few packages that provide Babel plugins
      # included in test configurations
      - uses: quilt-framework/action-build@v2
        with:
          command: pnpm build
          arguments: -- --only-project async --only-project workers
      - uses: quilt-framework/action-test@v2
        with:
          command: pnpm test
          arguments: -- --exclude-pattern tests/e2e

  e2e-tests:
    name: End-to-end tests ðŸ”¬
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/prepare
      - uses: quilt-framework/action-build@v2
        with:
          command: pnpm build
          arguments: --only-project package:*
      - uses: quilt-framework/action-test@v2
        with:
          command: pnpm test
          arguments: tests/e2e/
