name: CI

on: [push]

jobs:
  lint:
    name: Lint ðŸ’…
    runs-on: ubuntu-latest
    steps:
      - uses: quilt-framework/action-prepare@v1
      - uses: quilt-framework/action-lint@v2
        with:
          command: yarn lint

  type-check:
    name: Type check ðŸ§®
    runs-on: ubuntu-latest
    steps:
      - uses: quilt-framework/action-prepare@v1
      - uses: quilt-framework/action-type-check@v2
        with:
          command: yarn type-check

  unit-tests:
    name: Unit tests ðŸ§ª
    runs-on: ubuntu-latest
    steps:
      - uses: quilt-framework/action-prepare@v1
      - uses: quilt-framework/action-test@v2
        with:
          command: yarn test
          arguments: --exclude-pattern tests/e2e

  e2e-tests:
    name: End-to-end tests ðŸ”¬
    runs-on: ubuntu-latest
    steps:
      - uses: quilt-framework/action-prepare@v1
      - uses: quilt-framework/action-build@v2
        with:
          command: yarn build
          arguments: --only-project package:*
      - uses: quilt-framework/action-test@v2
        with:
          command: yarn test
          arguments: tests/e2e/
